### ISSUE TITLE
Collections Update

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [iShapeUnity/Mesh2d#1]
Hi there !

Is there any plan to update the package com.unity.collections to the 2.1.4 version ?

Anyway, great work !

**Comment by NailxSharipov** [comment]
Hey there,

Thanks for the heads-up! I've just updated com.unity.collections to version 2.1.4. So, make sure to pull the latest changes.

If you run into any other issues, don't hesitate to let me know. I will glad to help!

**Comment by EricBeetsOfficial-Opuscope** [comment]
Thank you so much !
